[phases.setup]
nixPkgs = ['python310', 'gcc', 'nodejs_18', 'npm-9_x']

[phases.build]
cmds = [
    'pip install -r requirements.txt',
    'cd frontend && npm install && npm run build',
    'mkdir -p static',
    'cp -r frontend/dist/* static/'
]

[start]
cmd = 'gunicorn start_website:app --bind 0.0.0.0:$PORT'